version: '2.1'

volumes:
  node-red-data:
  influxdb-data:
  influxdb-etc:
  grafana-data:


services: 

  # ------------------------------------------------------------------------------------
  # CO2
  # ------------------------------------------------------------------------------------
  co2:
    privileged: true
    build: "./co2"
    depends_on:
     - mqtt
    expose:
      - "2947"
      - "7575"
    labels:
      io.resin.features.dbus: '1'
      io.balena.features.kernel-modules: '1'
      io.balena.features.supervisor-api: '1'
      io.balena.features.balena-api: '1'
 
  # ------------------------------------------------------------------------------------
  # Node-RED
  # ------------------------------------------------------------------------------------
  node-red:
    image: bh.cr/balenalabs/balena-node-red
    container_name: node-red
    privileged: true
    restart: unless-stopped
    depends_on:
     - mqtt
    volumes:
        - 'node-red-data:/data'
    labels:
        io.balena.features.dbus: '1'
        io.balena.features.sysfs: '1'
        io.balena.features.supervisor-api: '1'
        io.balena.features.balena-api: '1'
    ports:
        - 80:80
    environment:
        PORT: 80
        USERNAME: "balena"
        PASSWORD: "balena"
        ENCRIPTION_KEY: "balena"        
    cap_add:
        - SYS_RAWIO
    devices:
        - "/dev/mem:/dev/mem"
        - "/dev/gpiomem:/dev/gpiomem"
        - "/dev/i2c-1:/dev/i2c-1"

  # ------------------------------------------------------------------------------------
  # Influxdb
  # ------------------------------------------------------------------------------------
  influxdb:
    image: influxdb:1.7.11
    container_name: influxdb
    restart: unless-stopped
    volumes:
        - influxdb-data:/var/lib/influxdb
        - influxdb-etc:/etc/influxdb

  # ------------------------------------------------------------------------------------
  # Grafana
  # ------------------------------------------------------------------------------------
  grafana:
    image: bh.cr/balenalabs/dashboard
    container_name: grafana
    restart: unless-stopped
    ports:
        - "8080:80"
    volumes:
        - "grafana-data:/data"

  # ------------------------------------------------------------------------------------
  # MQTT
  # ------------------------------------------------------------------------------------
  mqtt:
    image: eclipse-mosquitto:1.6.15
    ports:
      - "1883:1883"
    restart: always
  
  # ------------------------------------------------------------------------------------
  # Telegraf
  # ------------------------------------------------------------------------------------
  connector:
    image: balenablocks/connector
    restart: always
    depends_on:
     - mqtt
    privileged: true
    labels:
      io.balena.features.balena-api: '1'
